<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-08-23T19:02:19 IST" name="Suite" finished-at="2021-08-23T19:02:41 IST" duration-ms="22200">
    <groups>
    </groups>
    <test started-at="2021-08-23T19:02:19 IST" name="Test" finished-at="2021-08-23T19:02:41 IST" duration-ms="22200">
      <class name="Testcases.CreatenewAccount">
        <test-method is-config="true" signature="setUp()[pri:0, instance:Testcases.CreatenewAccount@16a0ee18]" started-at="2021-08-23T19:02:19 IST" name="setUp" finished-at="2021-08-23T19:02:34 IST" duration-ms="15624" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="mainTest()[pri:0, instance:Testcases.CreatenewAccount@16a0ee18]" started-at="2021-08-23T19:02:34 IST" name="mainTest" data-provider="createAcc" finished-at="2021-08-23T19:02:39 IST" duration-ms="5015" status="FAIL">
          <exception class="org.testng.internal.reflect.MethodMatcherException">
            <message>
              <![CDATA[
[public void Testcases.CreatenewAccount.mainTest() throws java.lang.Exception] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: mainTest([])
Arguments: [(java.lang.String) pngp@gmail.com,(java.lang.String) Mrs,(java.lang.String) TestUser,(java.lang.String) UserTest,(java.lang.String) hgsdtyf,(java.lang.String) 22,(java.lang.String) July ,(java.lang.String) 1985,(java.lang.String) ABCDEF,(java.lang.String) EDFG123,(java.lang.String) San,(java.lang.String) Alabama,(java.lang.String) 91436,(java.lang.String) United States,(java.lang.String) 8489875678]]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void Testcases.CreatenewAccount.mainTest() throws java.lang.Exception] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: mainTest([])
Arguments: [(java.lang.String) pngp@gmail.com,(java.lang.String) Mrs,(java.lang.String) TestUser,(java.lang.String) UserTest,(java.lang.String) hgsdtyf,(java.lang.String) 22,(java.lang.String) July ,(java.lang.String) 1985,(java.lang.String) ABCDEF,(java.lang.String) EDFG123,(java.lang.String) San,(java.lang.String) Alabama,(java.lang.String) 91436,(java.lang.String) United States,(java.lang.String) 8489875678]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:43)
at org.testng.internal.Parameters.injectParameters(Parameters.java:914)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:34)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.reflect.MethodMatcherException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mainTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Testcases.CreatenewAccount@16a0ee18]" started-at="2021-08-23T19:02:39 IST" name="tearDown" finished-at="2021-08-23T19:02:41 IST" duration-ms="1467" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Testcases.CreatenewAccount -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
